### PR TITLE
Split classpath by File.pathSeparator

### PR DESCRIPTION
**Pull request by bonifaido**
Otherwise the plugin is platform dependent. It doesn't work on Unixes, after this fix it will! :)

### CODE REVIEW

**Comment by gtache** [comment]
Nice catch! I must admit I had forgotten that Unixes don't use semicolon, and I didn't know pathSeparator.
Thanks!

**Comment by bonifaido** [comment]
Thanks! Otherwise it works fine!

**Comment by bonifaido** [comment]
I have some comments about the location of js files, the sbt plugin puts them into the target (build) folder, but with the plugin they land in the project root. Im curious why is it like that?

**Comment by gtache** [comment]
I thought it would be more convenient to have them in a dedicated folder in the project root, so that you can grab them more easily.
I can change this for the sake of convenience or consistency if you want.

**Comment by bonifaido** [comment]
Gradle and sbt puts generated sources under `build/target` so I think all plugins should follow the same convention. If so then even the plugin will get more simple because the `CleanAll` target can be removed.

**Comment by gtache** [comment]
It's done ;)

**Comment by bonifaido** [comment]
Great! Thank you for the quick reaction! 😊

**Pull request merged**
